using System.Text;

namespace StateMachineSrcGen.Generation;

/// <summary>
/// Applies consistent formatting, XML doc comments on public members,
/// and emits partial class declarations with correct namespace.
/// </summary>
internal static class SourceFormatter
{
    /// <summary>
    /// Wraps the generated class body in the proper file structure with
    /// auto-generated header, nullable enable, namespace, and partial class declaration.
    /// </summary>
    public static string Format(ValidatedStateMachine input, string classBody)
    {
        var sb = new StringBuilder();

        // Auto-generated header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {input.Namespace}");
        sb.AppendLine("{");

        // Class declaration with XML doc
        sb.AppendLine($"    /// <summary>Generated state machine implementation for {input.ClassName}.</summary>");
        sb.AppendLine($"    public static partial class {input.ClassName}");
        sb.AppendLine("    {");

        // Fields
        sb.AppendLine($"        /// <summary>The persistence provider for state storage.</summary>");
        sb.AppendLine($"        private static StateMachineSrcGen.IStatePersistence<{input.StateTypeName}> _persistence = new InMemoryPersistence();");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>The lock provider for concurrency control.</summary>");
        sb.AppendLine($"        private static StateMachineSrcGen.IStateLock<{input.StateTypeName}> _lock = new NoOpLock();");
        sb.AppendLine();

        // Class body (HandleAsync, nested classes)
        sb.Append(classBody);

        // Close class
        sb.AppendLine("    }");

        // Close namespace
        sb.AppendLine("}");

        return sb.ToString();
    }
}
